[app]
name = "alanswap"
port="8000"
apiPort = "8100"
version = "v1"
jwtSecret = "xxx"  # jwt secret
jwtTtl = 12  # token ttl in hours


[pgsql]
host = "localhost"
port = "5432"
database = "alanswap"
username = "alanuser"
password = "alanpasswd"

[redis]
host = "localhost"
port = "6379"
db = 1
password = ""
max_idle = 10
max_active = 0
idle_timeout = 180
poolSize=200


[[chains]]
name = "sepolia"
chain_id = 11155111
endpoint = "https://sepolia.infura.io/v3/96a918f215974f62b5db9a1907540819"

[monitor]
pprof_enable = true
pprof_port = 6060

[contract_cfg]
dex_address = "0x72e46e15ef83c896de44B1874B4AF7dDAB5b4F74" # undeploy